### ISSUE TITLE
MPU6050初始化失败

### ISSUE THREAD

**Issue by 197895** [LGQWakkk/MPU6050_DMP#1]
在这段函数中:
u8 MPU_Read_Byte(u8 reg)
{
	u8 res;
    MPU_IIC_Start(); 
	MPU_IIC_Send_Byte((MPU_ADDR<<1)|0);
	MPU_IIC_Wait_Ack();		
    MPU_IIC_Send_Byte(reg);	
    MPU_IIC_Wait_Ack();		
    MPU_IIC_Start();
	MPU_IIC_Send_Byte((MPU_ADDR<<1)|1);
    MPU_IIC_Wait_Ack();		
	res=MPU_IIC_Read_Byte(0);
    MPU_IIC_Stop();			
	return res;		
}

这个	MPU_IIC_Send_Byte((MPU_ADDR<<1)|0);
MPU_IIC_Wait_Ack();		//µÈ´ýÓ¦´ð 等待应答成功,但是
    MPU_IIC_Send_Byte(reg);	
    MPU_IIC_Wait_Ack();		//µÈ´ýÓ¦´ð等待应答失败
导致mpu_dmp_init()初始化失败

**Comment by LGQWakkk** [comment]
一般是不会出现这种问题的，可以考虑是不是引脚配置错误，硬件接触不良，硬件上下拉不合适等问题，如果想要排除这种问题的话可以修改如下函数查看是否正常：
u8 MPU_IIC_Wait_Ack(void)
{
	u8 ucErrTime=0;
	MPU_SDA_IN();      //SDA设置为输入  
	MPU_IIC_SDA=1;MPU_IIC_Delay();	   
	MPU_IIC_SCL=1;MPU_IIC_Delay();	 
	while(MPU_READ_SDA)
	{
		ucErrTime++;
		if(ucErrTime>250)
		{
			MPU_IIC_Stop();
			return 1;
		}
	}
	MPU_IIC_SCL=0;//时钟输出0 	   
	return 0;  
} 
将while里面的条件直接改为0，也就是不检测SDA电平直接略过，这样之后看看问题有没有解决？

**Comment by 197895** [comment]
我是硬件按照您的教程接好后,直接下载了您的文件,在keil5中打开并且build后上传,,不知道哪里还需要配置引脚?
然后我在keil5中用stlink进行调试,发现跳过了检测之后, 
MPU_IIC_Start();
	MPU_IIC_Send_Byte((MPU_ADDR<<1)|1);//·¢ËÍÆ÷¼þµØÖ·+¶ÁÃüÁî	
    MPU_IIC_Wait_Ack();		//µÈ´ýÓ¦´ð 
这三行会被跳过,且监视得出的res的值是0xD1 '?,也与MPU_ADDR不同.

**Comment by LGQWakkk** [comment]
你是调试才发现的卡在MPU_IIC_Wait_Ack();？

**Comment by LGQWakkk** [comment]
如果你没有修改要连接的GPIO的话是不需要配置引脚的

**Comment by 197895** [comment]
我就是一路调试过去才知道MPU_init初始化失败的

**Comment by LGQWakkk** [comment]
不调试也是不成功？

**Comment by LGQWakkk** [comment]
因为软件IIC是将本来一个完整的传输分为很多段了，所以就不能调试，因为这肯定是不符合IIC时序要求的，自然就会应答不成功。

**Comment by 197895** [comment]
直接接线也不成功

**Comment by 197895** [comment]
我用串口来供电,结果仍然卡在while(mpu_dmp_init())
我在while(mpu_dmp_init())里面加了USART1_SEND_BUF_U8(test,1);用来查看dmp是否初始化成功

**Comment by 197895** [comment]
补充一下,我用的是stm32f103c8t6,不知道要不要额外配置什么

**Comment by 197895** [comment]
数次重启和重新接线后解决
